// <auto-generated />
using System;
using AccountingHelper.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429153928_AddCreatedAtToEmployeeWithCorrectSalary")]
    partial class AddCreatedAtToEmployeeWithCorrectSalary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b44a5c2d-ebdb-4239-9b68-ca3837100840"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6860),
                            Department = "Engineering",
                            Email = "aigerim.nurlanova@contoso.kz",
                            FirstName = "Aigerim",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nurlanova",
                            Position = "Senior Software Engineer",
                            Salary = 85000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("ff5e3e20-4fdf-4946-b4ed-884bc51c44e4"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6860),
                            Department = "Engineering",
                            Email = "daniyar.akhmetov@contoso.kz",
                            FirstName = "Daniyar",
                            HireDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Akhmetov",
                            Position = "Engineering Manager",
                            Salary = 1200000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("f2ee2ca0-48cf-449e-addb-e2cc38048a89"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6870),
                            Department = "Design",
                            Email = "madina.serikova@contoso.kz",
                            FirstName = "Madina",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Serikova",
                            Position = "Product Designer",
                            Salary = 700000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("7b8d4444-1311-4b96-b00c-c2f3b09405a8"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6870),
                            Department = "Engineering",
                            Email = "yerlan.tursynov@contoso.kz",
                            FirstName = "Yerlan",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tursynov",
                            Position = "QA Engineer",
                            Salary = 550000m,
                            Status = "Fired",
                            TerminationDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5a13e76a-eec1-4095-9aca-22be39538931"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6870),
                            Department = "HR",
                            Email = "aliya.bekova@contoso.kz",
                            FirstName = "Aliya",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bekova",
                            Position = "HR Specialist",
                            Salary = 600000m,
                            Status = "OnVacation"
                        },
                        new
                        {
                            Id = new Guid("9c8f44b6-6c39-43d3-933e-fce7584b1530"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 39, 27, 958, DateTimeKind.Utc).AddTicks(6880),
                            Department = "Engineering",
                            Email = "ruslan.iskakov@contoso.kz",
                            FirstName = "Ruslan",
                            HireDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Iskakov",
                            Position = "DevOps Engineer",
                            Salary = 900000m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
