// <auto-generated />
using System;
using AccountingHelper.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430082145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("046e0b69-f987-4000-afad-f9b9fa2b6050"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1910),
                            Department = "Engineering",
                            Email = "aigerim.nurlanova@contoso.kz",
                            FirstName = "Aigerim",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nurlanova",
                            Position = "Senior Software Engineer",
                            Salary = 85000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("c912173c-db4a-4a87-9739-d5b82fe26400"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1910),
                            Department = "Engineering",
                            Email = "daniyar.akhmetov@contoso.kz",
                            FirstName = "Daniyar",
                            HireDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Akhmetov",
                            Position = "Engineering Manager",
                            Salary = 1200000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("73750a2b-5dba-4617-9363-085cc14f6e6d"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1920),
                            Department = "Design",
                            Email = "madina.serikova@contoso.kz",
                            FirstName = "Madina",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Serikova",
                            Position = "Product Designer",
                            Salary = 700000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0efb8546-825a-4692-893a-0cf3547770dd"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1920),
                            Department = "Engineering",
                            Email = "yerlan.tursynov@contoso.kz",
                            FirstName = "Yerlan",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tursynov",
                            Position = "QA Engineer",
                            Salary = 550000m,
                            Status = "Fired",
                            TerminationDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("630a08b1-637d-465d-8718-473d987fd045"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1930),
                            Department = "HR",
                            Email = "aliya.bekova@contoso.kz",
                            FirstName = "Aliya",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bekova",
                            Position = "HR Specialist",
                            Salary = 600000m,
                            Status = "OnVacation"
                        },
                        new
                        {
                            Id = new Guid("ab2d8a30-d5af-4f6e-8d4e-165690b4ba35"),
                            CreatedAt = new DateTime(2026, 4, 30, 8, 21, 45, 172, DateTimeKind.Utc).AddTicks(1930),
                            Department = "Engineering",
                            Email = "ruslan.iskakov@contoso.kz",
                            FirstName = "Ruslan",
                            HireDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Iskakov",
                            Position = "DevOps Engineer",
                            Salary = 900000m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
