// <auto-generated />
using System;
using AccountingHelper.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429153740_AddCreatedAtToEmployee")]
    partial class AddCreatedAtToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9ef064f-48d9-43da-86b9-47e5dd32f76f"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1240),
                            Department = "Engineering",
                            Email = "aigerim.nurlanova@contoso.kz",
                            FirstName = "Aigerim",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nurlanova",
                            Position = "Senior Software Engineer",
                            Salary = 85000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("cbd36a56-9cdd-4911-bb83-0ffe6e6781b8"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1240),
                            Department = "Engineering",
                            Email = "daniyar.akhmetov@contoso.kz",
                            FirstName = "Daniyar",
                            HireDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Akhmetov",
                            Position = "Engineering Manager",
                            Salary = 1200000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("7df96215-6563-403b-97e2-781e7b65b50a"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1250),
                            Department = "Design",
                            Email = "madina.serikova@contoso.kz",
                            FirstName = "Madina",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Serikova",
                            Position = "Product Designer",
                            Salary = 700000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("224f409b-c60e-43a8-aad7-e78134ce5130"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1250),
                            Department = "Engineering",
                            Email = "yerlan.tursynov@contoso.kz",
                            FirstName = "Yerlan",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tursynov",
                            Position = "QA Engineer",
                            Salary = 550000m,
                            Status = "Fired",
                            TerminationDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f891cfe-5f0d-4997-926d-6928702147e1"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1260),
                            Department = "HR",
                            Email = "aliya.bekova@contoso.kz",
                            FirstName = "Aliya",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bekova",
                            Position = "HR Specialist",
                            Salary = 600000m,
                            Status = "OnVacation"
                        },
                        new
                        {
                            Id = new Guid("b1cb6b2f-8277-4896-a0bd-72e10d9733ff"),
                            CreatedAt = new DateTime(2026, 4, 29, 15, 37, 40, 538, DateTimeKind.Utc).AddTicks(1260),
                            Department = "Engineering",
                            Email = "ruslan.iskakov@contoso.kz",
                            FirstName = "Ruslan",
                            HireDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Iskakov",
                            Position = "DevOps Engineer",
                            Salary = 900000m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
