// <auto-generated />
using System;
using AccountingHelper.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingHelper.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "66a5203d-519d-4a64-9aa2-44dd55fa0c5a",
                            Department = "Engineering",
                            Email = "aigerim.nurlanova@contoso.kz",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aigerim Nurlanova",
                            Position = "Senior Software Engineer",
                            Salary = 85000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = "60a5eae8-a941-410f-b215-650222262f55",
                            Department = "Engineering",
                            Email = "daniyar.akhmetov@contoso.kz",
                            HireDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniyar Akhmetov",
                            Position = "Engineering Manager",
                            Salary = 1200000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = "a93249a9-842f-4b55-b594-f49711dfb7fd",
                            Department = "Design",
                            Email = "madina.serikova@contoso.kz",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Madina Serikova",
                            Position = "Product Designer",
                            Salary = 700000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = "658fddf0-11f6-4c59-8622-3fa8af588e0b",
                            Department = "Engineering",
                            Email = "yerlan.tursynov@contoso.kz",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yerlan Tursynov",
                            Position = "QA Engineer",
                            Salary = 550000m,
                            Status = "Terminated",
                            TerminationDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "8aaeff3d-e216-49d7-9e03-8f46a3f82a7f",
                            Department = "HR",
                            Email = "aliya.bekova@contoso.kz",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aliya Bekova",
                            Position = "HR Specialist",
                            Salary = 600000m,
                            Status = "OnLeave"
                        },
                        new
                        {
                            Id = "0f48f0d8-00bc-4ed4-805b-4c41efdb2f42",
                            Department = "Engineering",
                            Email = "ruslan.iskakov@contoso.kz",
                            HireDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ruslan Iskakov",
                            Position = "DevOps Engineer",
                            Salary = 900000m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
