// <auto-generated />
using System;
using AccountingHelper.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountingHelper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731085819_AddLeaveManagement")]
    partial class AddLeaveManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.DepartmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employees_position_id");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Email = "aigerim.nurlanova@contoso.kz",
                            FirstName = "Aigerim",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nurlanova",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000001"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Email = "daniyar.akhmetov@contoso.kz",
                            FirstName = "Daniyar",
                            HireDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Akhmetov",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000002"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Email = "madina.serikova@contoso.kz",
                            FirstName = "Madina",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Serikova",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Email = "yerlan.tursynov@contoso.kz",
                            FirstName = "Yerlan",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Tursynov",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000004"),
                            Status = "Fired",
                            TerminationDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Email = "aliya.bekova@contoso.kz",
                            FirstName = "Aliya",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Bekova",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000005"),
                            Status = "OnVacation"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Email = "ruslan.iskakov@contoso.kz",
                            FirstName = "Ruslan",
                            HireDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Iskakov",
                            PositionId = new Guid("33333333-0000-0000-0000-000000000006"),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.LeaveBalanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("leave_type");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_leave_balances");

                    b.HasIndex("EmployeeId", "LeaveType")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_balances_employee_id_leave_type");

                    b.ToTable("leave_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_leave_balances_remaining_days", "remaining_days >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            LeaveType = "Annual",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            LeaveType = "Annual",
                            RemainingDays = 28
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            LeaveType = "Annual",
                            RemainingDays = 28
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            LeaveType = "Annual",
                            RemainingDays = 28
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            LeaveType = "Annual",
                            RemainingDays = 16
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000006"),
                            LeaveType = "Annual",
                            RemainingDays = 28
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000004"),
                            CreatedAt = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000005"),
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0001-000000000006"),
                            CreatedAt = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000006"),
                            LeaveType = "Sick",
                            RemainingDays = 14
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000001"),
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000002"),
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000003"),
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000004"),
                            CreatedAt = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000005"),
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0002-000000000006"),
                            CreatedAt = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000006"),
                            LeaveType = "Unpaid",
                            RemainingDays = 30
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.LeaveRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("leave_type");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_leave_requests_employee_id_status");

                    b.ToTable("leave_requests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecidedAt = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            EndDate = new DateOnly(2024, 7, 14),
                            LeaveType = "Annual",
                            RequestedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2024, 7, 1),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            EndDate = new DateOnly(2026, 8, 7),
                            LeaveType = "Sick",
                            RequestedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2026, 8, 3),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            EndDate = new DateOnly(2026, 8, 20),
                            LeaveType = "Annual",
                            RequestedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2026, 8, 10),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecidedAt = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            EndDate = new DateOnly(2024, 10, 10),
                            LeaveType = "Annual",
                            RequestedAt = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2024, 10, 1),
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecidedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            EndDate = new DateOnly(2026, 8, 7),
                            LeaveType = "Annual",
                            RequestedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2026, 7, 27),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecidedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000006"),
                            EndDate = new DateOnly(2026, 9, 3),
                            LeaveType = "Unpaid",
                            RequestedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2026, 9, 1),
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Senior",
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Lead",
                            Title = "Engineering Manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Middle",
                            Title = "Product Designer"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Middle",
                            Title = "QA Engineer"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Junior",
                            Title = "HR Specialist"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "Senior",
                            Title = "DevOps Engineer"
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.SalaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_salaries");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_salaries_employee_id");

                    b.ToTable("salaries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            Amount = 850000m,
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Type = "Monthly"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            Amount = 1200000m,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Type = "Monthly"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            Amount = 700000m,
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Type = "Monthly"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            Amount = 550000m,
                            CreatedAt = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            Type = "Monthly"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            Amount = 600000m,
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            Type = "Monthly"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000006"),
                            Amount = 900000m,
                            CreatedAt = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("11111111-0000-0000-0000-000000000006"),
                            Type = "Monthly"
                        });
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("AccountingHelper.Infrastructure.Data.Entities.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.HasOne("AccountingHelper.Infrastructure.Data.Entities.PositionEntity", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_positions_position_id");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.LeaveBalanceEntity", b =>
                {
                    b.HasOne("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_balances_employees_employee_id");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.LeaveRequestEntity", b =>
                {
                    b.HasOne("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.SalaryEntity", b =>
                {
                    b.HasOne("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salaries_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("AccountingHelper.Infrastructure.Data.Entities.PositionEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
